### ISSUE TITLE
"name is already taken" after a pod version delete

### ISSUE THREAD

**Issue by andr3a88** [CocoaPods/trunk.cocoapods.org#172]
I've deleted a pod version with `pod trunk delete ASProgressHud.podspec 0.0.1`, now i'm trying to push the version 0.0.2,  but when i pushe again i've this error **[!] {"name"=>["is already taken"]}**

**Comment by segiddins** [comment]
Are you sure you're the owner of that pod?

**Comment by andr3a88** [comment]
yes...

[https://github.com/CocoaPods/Specs/commit/90020d1888a1b1a0a9d49088e17eda22d2517dfe](url)

[https://github.com/CocoaPods/Specs/commit/2b18fc6be208d80399bd8e86075d16a463050b37](url)

**Comment by segiddins** [comment]
What's the output of `pod trunk me`?

**Comment by andr3a88** [comment]
```
pod trunk info ASProgressHud
[!] No pod found with the specified name.


MacBook-Air:ASProgressHud andrea$ pod trunk me
  - Name:     Andrea
  - Email:   myEmail
  - Since:    February 19th, 17:38
  - Pods:
    - ASProgressHud
  - Sessions:
    - February 19th, 17:38 - June 26th, 18:06. IP:-----    Description: iMac
    - February 19th, 19:09 - June 27th, 11:09. IP: ----- Description: macbook-air
```

**Comment by andr3a88** [comment]
@segiddins any suggestions?

**Comment by orta** [comment]
Do we un-delete pods if all versions were deleted and someone adds a new one /cc @floere ?

**Comment by segiddins** [comment]
@orta in theory ;)
I've been busy this weekend, I'll try and read through the relevant code tonight.

**Comment by floere** [comment]
@orta As far as I can see, we don't undelete pods even if a new, undeleted version is added. We should probably handle that in `handle_modified` – a symmetrical method of `delete_versionless`. Would you agree, @segiddins ?

**Comment by AndreaStevanato** [comment]
you can delete the pod so I can resend it?

**Comment by andr3a88** [comment]
you can delete the pod so I can resend it?

**Comment by ricardopereira** [comment]
@andr3a88 I'm with the same problem. Any updates?

**Comment by segiddins** [comment]
Trying to debug with a local version of the trunk app is probably your best for the meantime -- we're unlikely to get around to this issue immediately.

**Comment by mattheworiordan** [comment]
@segiddins any update on this?  It's been almost a month that we've been unable to deploy our pod.  Any help would be appreciated. Is there no manual clean up that could be done as a once off please?

**Comment by orta** [comment]
@mattheworiordan I'm afraid we've been busy with 1.0 and the changes we've had to make for github -  I've manually marked ASProgressHud as not-deleted in the db, you should check to see if that works.

**Comment by mattheworiordan** [comment]
> I've manually marked ASProgressHud as not-deleted in the db, you should check to see if that works.

Thanks for the reply @orta , but unfortunately I am not sure what you are referring to with `ASProgressHud`?  I have tried `$ pod trunk push` again now and still get `[!] {"name"=>["is already taken"]}` for our pod Ably

**Comment by orta** [comment]
Oh, well, you didn't really say what your Pod was, I just assumed was that as it was brought up earlier. I've marked that as not deleted too.

**Comment by mattheworiordan** [comment]
Thanks @orta, sorry for the confusion, our original issue was https://github.com/CocoaPods/CocoaPods/issues/5020 which was closed in favour of this one.

Here's my push which is still failing unfortunately:

```
$ pod trunk push

[!] Found podspec `Ably.podspec`
Updating spec repo `master`

CocoaPods 1.0.0.beta.6 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Validating podspec
 -> Ably (0.8.0-beta.1)

[!] {"name"=>["is already taken"]}
```

Here is our Podspec if that helps at all:
```
Pod::Spec.new do |s|
  s.name              = "Ably"
  s.version           = "0.8.0-beta.1"
  s.summary           = "iOS client for Ably"
  s.description       = <<-DESC
                        iOS client library for ably.io, the realtime messaging service, written in Objective-C and ready for Swift 2.0.
                        DESC
  s.homepage          = "https://www.ably.io"
  s.license           = { :type => 'Apache 2.0', :file => 'LICENSE' }
  s.author            = { "Ably" => "support@ably.io" }
  s.source            = { :git => "https://github.com/ably/ably-ios.git", :tag => s.version.to_s }
  s.requires_arc      = true
  s.social_media_url  = 'https://twitter.com/ablyrealtime'
  s.documentation_url = "https://www.ably.io/documentation"
  s.platform          = :ios, '8.0'
  s.requires_arc      = true
  s.source_files      = 'Source/*.{h,m}'
  s.module_map        = 'Source/Ably.modulemap'
  s.pod_target_xcconfig = { 'HEADER_SEARCH_PATHS' => '$CONFIGURATION_BUILD_DIR/SwiftWebSocket.framework/Headers' }
  s.dependency 'SwiftWebSocket', '~> 2.5'
end
```

**Comment by ricardopereira** [comment]
Thanks @orta. I changed the pod lowercase name to capital (`ably` -> `Ably`). Any inconvenient with this on updating?

**Comment by orta** [comment]
Looks like the work needed in this issue needs to be done I'm afraid then, PRs welcome to boost it's time, we can't guarantee our time anytime soon given that I'm flying a lot from today, and the rest of the team is focusing their time on 1.0 and not crippling github's infrastructure

**Comment by mattheworiordan** [comment]
Ok, thanks for the heads up @orta, we'll probably just go with another name for now

**Comment by segiddins** [comment]
@alloy or @floere if either of you have some spare cycles, taking a look into this would be much appreciated!

**Comment by viacheslavleonov** [comment]
Could you please undelete my pod 'ampiri-ios-sdk' as long as this bug is not fixed yet?

**Comment by segiddins** [comment]
I've just deployed the fix for this -- thanks for hanging with us!

**Comment by tcard** [comment]
@segiddins Thanks, but `Ably` stills seems to be unavailable. Still the same `[!] {"name"=>["is already taken"]}`error. /@mattheworiordan ably/ably-ios#290
